title: FRAN MARTINEZ PORTFOLIO
description: Fran Martinez Portfolio by Jekyll
theme: just-the-docs

url: https://franmaral.github.io/portfolio/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
